# ============================================================
# Script: corrigir-supabase-logs-v2.ps1
# Autor: Richeles + GPT-5
# Objetivo: criar e habilitar logs_reparo via REST oficial
# ============================================================

Write-Host "🚀 Iniciando correção do Supabase (v2)..." -ForegroundColor Cyan

# === CONFIGURAÇÕES ===
$SUPABASE_URL = "https://kpzzekflqpoeccnqfkng.supabase.co"
$SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwenpla2ZscXBvZWNjbnFma25nIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDgwNzE1MiwiZXhwIjoyMDY2MzgzMTUyfQ.8zy_xc93iJVdrIPrdP-iy8XN9GlVWkE0epmrguca3iA"

# === SQL de criação ===
$sql = @"
CREATE TABLE IF NOT EXISTS public.logs_reparo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_execucao TIMESTAMPTZ DEFAULT now(),
  arquivos_verificados INT,
  arquivos_corrigidos INT,
  arquivos_padronizados INT,
  mensagem TEXT,
  sucesso BOOLEAN DEFAULT TRUE
);

ALTER TABLE public.logs_reparo ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'logs_reparo'
      AND policyname = 'Permitir insercoes via API'
  ) THEN
    CREATE POLICY "Permitir insercoes via API"
      ON public.logs_reparo
      FOR INSERT TO public
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;
"@

# === EXECUTAR SQL ===
try {
    Invoke-RestMethod -Uri "$SUPABASE_URL/rest/v1/rpc/sql" `
        -Method Post `
        -Headers @{
            "apikey" = $SUPABASE_SERVICE_KEY
            "Authorization" = "Bearer $SUPABASE_SERVICE_KEY"
            "Content-Type" = "application/json"
        } `
        -Body (@{ q = $sql } | ConvertTo-Json) | Out-Null
    Write-Host "✅ Tabela e política criadas com sucesso!" -ForegroundColor Green
}
catch {
    Write-Host "⚠️ Falha ao executar SQL: $($_.Exception.Message)" -ForegroundColor Red
}

# === TESTE DE ENDPOINT ===
try {
    $testBody = @{
        arquivos_verificados = 1
        arquivos_corrigidos  = 0
        arquivos_padronizados = 1
        mensagem = "Teste automático de logs_reparo"
        sucesso = $true
    } | ConvertTo-Json

    Invoke-RestMethod -Uri "$SUPABASE_URL/rest/v1/logs_reparo" `
        -Method Post `
        -Headers @{
            "apikey" = $SUPABASE_SERVICE_KEY
            "Authorization" = "Bearer $SUPABASE_SERVICE_KEY"
            "Content-Type" = "application/json"
            "Prefer" = "return=minimal"
        } `
        -Body $testBody

    Write-Host "☁️ Endpoint REST ativo e inserção bem-sucedida!" -ForegroundColor Green
}
catch {
    Write-Host "❌ Erro ao testar endpoint: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host "`n🏁 Processo concluído. Se 'Endpoint REST ativo' aparecer, o 404 foi resolvido." -ForegroundColor Cyan
Write-Host "💡 Em seguida rode .\reparar-bom-v4.1.ps1" -ForegroundColor White
