# ============================================================
# Script: corrigir-e-reparar-supabase.ps1
# Autor: Richeles + GPT-5
# Objetivo: Corrigir endpoint 404 do Supabase, criar logs_reparo e executar reparo automático
# ============================================================

Write-Host "🚀 Iniciando correção do Supabase e auto-reparo (vFinal)..." -ForegroundColor Cyan

# === CONFIGURAÇÕES ===
$pasta = "C:\Users\Administrador\pecuariatech"
$SUPABASE_URL = "https://kpzzekflqpoeccnqfkng.supabase.co"
$SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwenpla2ZscXBvZWNjbnFma25nIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDgwNzE1MiwiZXhwIjoyMDY2MzgzMTUyfQ.8zy_xc93iJVdrIPrdP-iy8XN9GlVWkE0epmrguca3iA"

# === SQL DE CRIAÇÃO ===
$sql = @"
create table if not exists public.logs_reparo (
  id bigint generated by default as identity primary key,
  data_execucao timestamptz default now(),
  arquivos_verificados int,
  arquivos_corrigidos int,
  arquivos_padronizados int,
  mensagem text,
  sucesso boolean default true
);
alter table public.logs_reparo enable row level security;
create policy if not exists "Permitir insercoes via API"
on public.logs_reparo
for insert
to public
using (true)
with check (true);
"@

# === CRIAR A TABELA VIA SQL API ===
try {
    $response = Invoke-RestMethod `
      -Uri "$SUPABASE_URL/sql/v1" `
      -Method Post `
      -Headers @{
          "apikey" = $SUPABASE_SERVICE_KEY
          "Authorization" = "Bearer $SUPABASE_SERVICE_KEY"
          "Content-Type" = "application/json"
      } `
      -Body (@{ query = $sql } | ConvertTo-Json)

    Write-Host "✅ Tabela logs_reparo criada e políticas aplicadas!" -ForegroundColor Green
}
catch {
    Write-Host "❌ Erro ao criar tabela: $($_.Exception.Message)" -ForegroundColor Red
}

# === TESTAR ENDPOINT REST ===
try {
    $testBody = @{
        arquivos_verificados = 5
        arquivos_corrigidos = 1
        arquivos_padronizados = 4
        mensagem = "Teste automático de logs_reparo"
        sucesso = $true
    } | ConvertTo-Json

    Invoke-RestMethod -Uri "$SUPABASE_URL/rest/v1/logs_reparo" `
        -Method Post `
        -Headers @{
            "apikey" = $SUPABASE_SERVICE_KEY
            "Authorization" = "Bearer $SUPABASE_SERVICE_KEY"
            "Content-Type" = "application/json"
            "Prefer" = "return=minimal"
        } `
        -Body $testBody

    Write-Host "☁️ Endpoint REST ativo e inserção bem-sucedida!" -ForegroundColor Green
}
catch {
    Write-Host "⚠️ Erro ao testar endpoint REST: $($_.Exception.Message)" -ForegroundColor Yellow
}

# === EXECUTAR O REPARO FINAL ===
if (Test-Path "$pasta\reparar-bom-v4.1.ps1") {
    Write-Host "`n🧩 Executando reparo automático (reparar-bom-v4.1.ps1)..." -ForegroundColor Cyan
    & "$pasta\reparar-bom-v4.1.ps1"
} else {
    Write-Host "⚠️ Script reparar-bom-v4.1.ps1 não encontrado no diretório." -ForegroundColor Red
}

Write-Host "`n🏁 Processo completo concluído!" -ForegroundColor Cyan
Write-Host "💡 Acesse seu Supabase → Table Editor → logs_reparo para ver o resultado." -ForegroundColor White
