# ============================================================
# Script: corrigir-supabase-logs.ps1
# Autor: Richeles + GPT-5
# Objetivo: Corrigir erros 404 e garantir endpoint REST funcional no Supabase
# ============================================================

Write-Host "🚀 Iniciando correção da tabela logs_reparo no Supabase..." -ForegroundColor Cyan

# === CONFIGURAÇÕES ===
$SUPABASE_URL = "https://kpzzekflqpoeccnqfkng.supabase.co"
$SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwenpla2ZscXBvZWNjbnFma25nIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDgwNzE1MiwiZXhwIjoyMDY2MzgzMTUyfQ.8zy_xc93iJVdrIPrdP-iy8XN9GlVWkE0epmrguca3iA"

# === CRIAÇÃO DA TABELA E POLÍTICAS ===
Write-Host "📦 Verificando e criando tabela logs_reparo..." -ForegroundColor Yellow

$SQL = @"
create table if not exists public.logs_reparo (
  id bigint generated by default as identity primary key,
  data_execucao timestamptz default now(),
  arquivos_verificados int,
  arquivos_corrigidos int,
  arquivos_padronizados int,
  mensagem text,
  sucesso boolean default true
);

alter table public.logs_reparo enable row level security;

drop policy if exists "Permitir inserções via API" on public.logs_reparo;

create policy "Permitir inserções via API"
on public.logs_reparo
for insert
to public
using (true)
with check (true);
"@

# Envio do SQL ao Supabase
$response = Invoke-RestMethod -Uri "$SUPABASE_URL/rest/v1/rpc/exec_sql" `
  -Method Post `
  -Headers @{
    "apikey" = $SUPABASE_SERVICE_KEY
    "Authorization" = "Bearer $SUPABASE_SERVICE_KEY"
    "Content-Type" = "application/json"
  } `
  -Body (@{ sql = $SQL } | ConvertTo-Json)

Write-Host "✅ Tabela e políticas recriadas com sucesso!" -ForegroundColor Green

# === TESTE DO ENDPOINT ===
Write-Host "🔍 Testando endpoint REST..." -ForegroundColor Cyan

try {
    $testBody = @{
        arquivos_verificados = 1
        arquivos_corrigidos = 0
        arquivos_padronizados = 1
        mensagem = "Teste automático de conexão"
        sucesso = $true
    } | ConvertTo-Json

    Invoke-RestMethod -Uri "$SUPABASE_URL/rest/v1/logs_reparo" `
        -Method Post `
        -Headers @{
            "apikey" = $SUPABASE_SERVICE_KEY
            "Authorization" = "Bearer $SUPABASE_SERVICE_KEY"
            "Content-Type" = "application/json"
            "Prefer" = "return=minimal"
        } `
        -Body $testBody

    Write-Host "☁️ Endpoint REST do Supabase ativo e funcional!" -ForegroundColor Green
}
catch {
    Write-Host "❌ Erro ao testar endpoint: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host "`n🏁 Processo concluído. O Supabase está sincronizado e pronto para uso." -ForegroundColor Cyan
Write-Host "💡 Dica: Agora rode .\reparar-bom-v4.1.ps1 para enviar logs reais." -ForegroundColor White
