Write-Host "🚀 Criando tabela logs_reparo diretamente no banco Supabase..." -ForegroundColor Cyan

# URL de conexão com senha codificada (%40 no lugar do @)
$connectionString = "postgresql://postgres:36%40Artropodes@db.kpzzekflqpoeccnqfkng.supabase.co:5432/postgres"

# Verifica se o cliente PostgreSQL está instalado
if (-not (Get-Command psql -ErrorAction SilentlyContinue)) {
    Write-Host "⚠️ Cliente PostgreSQL não encontrado. Instalando..." -ForegroundColor Yellow
    winget install PostgreSQL
}

# Comando SQL
$sql = @"
create table if not exists public.logs_reparo (
  id bigint generated by default as identity primary key,
  data_execucao timestamptz default now(),
  arquivos_verificados int,
  arquivos_corrigidos int,
  arquivos_padronizados int,
  mensagem text,
  sucesso boolean default true
);

alter table public.logs_reparo enable row level security;

drop policy if exists "Permitir insercoes via API" on public.logs_reparo;

create policy "Permitir insercoes via API"
on public.logs_reparo
for insert
to public
with check (true);
"@

# Executa o comando no banco remoto
psql $connectionString -c $sql

Write-Host "✅ Tabela logs_reparo criada e configurada com sucesso!" -ForegroundColor Green
