# ============================================================
# Script: criar-tabela-logs.ps1
# Autor: Richeles + GPT-5
# Descrição: Cria a tabela logs_reparo no Supabase via PowerShell (API SQL)
# ============================================================

Write-Host "🚀 Iniciando criação da tabela logs_reparo no Supabase..." -ForegroundColor Cyan

# === CONFIGURAÇÕES ===
$SUPABASE_URL = "https://kpzzekflqpoeccnqfkng.supabase.co"
$SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwenpla2ZscXBvZWNjbnFma25nIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDgwNzE1MiwiZXhwIjoyMDY2MzgzMTUyfQ.8zy_xc93iJVdrIPrdP-iy8XN9GlVWkE0epmrguca3iA"

# === COMANDO SQL ===
$sql = @"
create table if not exists public.logs_reparo (
  id bigint generated by default as identity primary key,
  data_execucao timestamptz default now(),
  arquivos_verificados int,
  arquivos_corrigidos int,
  arquivos_padronizados int,
  mensagem text,
  sucesso boolean default true
);

alter table public.logs_reparo enable row level security;

drop policy if exists "Permitir insercoes via API" on public.logs_reparo;

create policy "Permitir insercoes via API"
on public.logs_reparo
for insert
to public
with check (true);
"@

# === EXECUTAR NO SUPABASE ===
try {
    $body = @{ query = $sql } | ConvertTo-Json -Depth 5

    $response = Invoke-RestMethod `
        -Uri "$SUPABASE_URL/sql/v1" `
        -Method Post `
        -Headers @{
            "apikey" = $SUPABASE_SERVICE_KEY
            "Authorization" = "Bearer $SUPABASE_SERVICE_KEY"
            "Content-Type" = "application/json"
        } `
        -Body $body

    Write-Host "✅ Tabela logs_reparo criada com sucesso!" -ForegroundColor Green
}
catch {
    Write-Host "❌ Erro ao criar tabela: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host "🏁 Processo concluído. Verifique no Supabase → Table Editor → logs_reparo." -ForegroundColor Cyan
