Write-Host "🔺 Sistema Triangular 360° — Modo Adaptive Iniciado..." -ForegroundColor Cyan

# ==== 🔐 Senha segura =========================================================
$senhaArquivo = "$env:APPDATA\supabase_cred.key"
if (-not (Test-Path $senhaArquivo)) {
    Write-Host "🔑 Criando nova credencial segura..."
    $senha = Read-Host "Digite sua senha do banco Supabase (ex: 36@Artropodes)" -AsSecureString
    $senha | ConvertFrom-SecureString | Out-File $senhaArquivo
}
$senha = Get-Content $senhaArquivo | ConvertTo-SecureString
$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($senha)
$senhaPura = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
$senhaCodificada = [uri]::EscapeDataString($senhaPura)

# ==== 🌐 Configuração =========================================================
$DB_URL = "db.kpzzekflqpoeccnqfkng.supabase.co"
$PSQL_PATH = "C:\Program Files\PostgreSQL\17\bin\psql.exe"
$LOG_FILE = "C:\Users\Administrador\pecuariatech\tri360_secure_log.txt"
$connectionString = "postgresql://postgres:$senhaCodificada@$DB_URL:5432/postgres"

# ==== 🧠 1️⃣ Verificação de ambiente ==========================================
Write-Host "🧠 [1/4] Diagnóstico do ambiente..."
if (-not (Test-Path $PSQL_PATH)) {
    Write-Host "⚙️ Instalando cliente PostgreSQL..." -ForegroundColor Yellow
    winget install --source winget PostgreSQL.PostgreSQL.17
}
$env:PATH += ";C:\Program Files\PostgreSQL\17\bin"

# ==== 🌍 2️⃣ Conexão ==========================================================
Write-Host "🌐 [2/4] Testando conexão com Supabase..."
try {
    $test = & $PSQL_PATH $connectionString -c "SELECT version();" 2>&1
    if ($test -match "PostgreSQL") { Write-Host "✅ Conectado ao Supabase." }
    else { throw "Falha: $test" }
}
catch {
    Write-Host "❌ Erro ao conectar. Verifique credenciais ou rede." -ForegroundColor Red
    exit
}

# ==== 🧩 3️⃣ Criação e sincronização ==========================================
Write-Host "🧩 [3/4] Verificando e criando tabela logs_reparo..."
$sql = @"
create table if not exists public.logs_reparo (
  id bigint generated by default as identity primary key,
  data_execucao timestamptz default now(),
  arquivos_verificados int,
  arquivos_corrigidos int,
  arquivos_padronizados int,
  mensagem text,
  sucesso boolean default true
);
alter table public.logs_reparo enable row level security;
drop policy if exists "Permitir insercoes via API" on public.logs_reparo;
create policy "Permitir insercoes via API"
on public.logs_reparo
for insert
to public
with check (true);
"@
& $PSQL_PATH $connectionString -c $sql
Write-Host "✅ Tabela verificada e ativa." -ForegroundColor Green

# ==== 📑 4️⃣ Log adaptativo ===================================================
if (-not (Test-Path $LOG_FILE)) {
    Write-Host "🧾 Criando log inicial..."
    New-Item -Path $LOG_FILE -ItemType File -Force | Out-Null
}
$mensagem = "Tri360-Adaptive executado com sucesso em $(Get-Date)"
Add-Content $LOG_FILE $mensagem

# Recalcula hash após criação
$hash = (Get-FileHash $LOG_FILE -Algorithm SHA256).Hash
Add-Content $LOG_FILE "Hash SHA256: $hash"

Write-Host "📁 Log atualizado em: $LOG_FILE" -ForegroundColor Yellow
Write-Host "🔺 Sistema Triangular 360° — Adaptive concluído com sucesso." -ForegroundColor Cyan
