Write-Host "🔺 Sistema Triangular 360° — Autorreparo Supabase iniciado..." -ForegroundColor Cyan

# ===================== CONFIGURAÇÃO BASE =====================
$SENHA = "36@Artropodes"
$SENHA_URL = "36%40Artropodes"
$DB_URL = "db.kpzzekflqpoeccnqfkng.supabase.co"
$PSQL_PATH = "C:\Program Files\PostgreSQL\17\bin\psql.exe"
$LOG_FILE = "C:\Users\Administrador\pecuariatech\tri360_log.txt"

# ===================== 1️⃣ VERIFICAÇÃO =====================
Write-Host "🧠 [1/4] Diagnóstico inicial..."
if (-not (Test-Path $PSQL_PATH)) {
    Write-Host "⚠️ Cliente PostgreSQL não encontrado. Instalando..." -ForegroundColor Yellow
    winget install --source winget PostgreSQL.PostgreSQL.17
} else {
    Write-Host "✅ Cliente PostgreSQL detectado."
}

# Testa PATH
$env:PATH += ";C:\Program Files\PostgreSQL\17\bin"

# ===================== 2️⃣ TESTE DE CONEXÃO =====================
Write-Host "🌐 [2/4] Testando conexão com Supabase..."
$connectionString = "postgresql://postgres:$SENHA_URL@$DB_URL:5432/postgres"
try {
    $test = & $PSQL_PATH $connectionString -c "SELECT version();" 2>&1
    if ($test -match "PostgreSQL") {
        Write-Host "✅ Conexão estabelecida com Supabase."
    } else {
        throw "Falha ao conectar. Detalhes: $test"
    }
}
catch {
    Write-Host "❌ Erro na conexão com o Supabase. Verifique a senha ou internet." -ForegroundColor Red
    Add-Content $LOG_FILE "[$(Get-Date)] Falha de conexão: $_"
    exit
}

# ===================== 3️⃣ REPARO E CRIAÇÃO =====================
Write-Host "🧩 [3/4] Criando tabela logs_reparo..."
$sql = @"
create table if not exists public.logs_reparo (
  id bigint generated by default as identity primary key,
  data_execucao timestamptz default now(),
  arquivos_verificados int,
  arquivos_corrigidos int,
  arquivos_padronizados int,
  mensagem text,
  sucesso boolean default true
);
alter table public.logs_reparo enable row level security;
drop policy if exists "Permitir insercoes via API" on public.logs_reparo;
create policy "Permitir insercoes via API"
on public.logs_reparo
for insert
to public
with check (true);
"@

try {
    & $PSQL_PATH $connectionString -c $sql
    Write-Host "✅ Tabela logs_reparo criada e configurada." -ForegroundColor Green
}
catch {
    Write-Host "❌ Falha ao criar tabela no Supabase." -ForegroundColor Red
    Add-Content $LOG_FILE "[$(Get-Date)] Erro de SQL: $_"
}

# ===================== 4️⃣ LOG E SINCRONIZAÇÃO =====================
Write-Host "📡 [4/4] Registrando log de operação..."
$mensagem = "Execução Triangular360 finalizada com sucesso"
Add-Content $LOG_FILE "[$(Get-Date)] $mensagem"

Write-Host "✅ Processo completo concluído!"
Write-Host "📁 Log salvo em: $LOG_FILE" -ForegroundColor Yellow
Write-Host "🔺 Sistema Triangular 360° concluído com estabilidade total." -ForegroundColor Cyan
