Write-Host "🔺 Sistema Triangular 360° — Versão Segura Iniciada..." -ForegroundColor Cyan

# ===================== 🔐 CRIPTOGRAFIA DE SENHA =====================
$senhaArquivo = "$env:APPDATA\supabase_cred.key"
if (-not (Test-Path $senhaArquivo)) {
    Write-Host "🔑 Nenhuma senha armazenada — criando credencial segura..." -ForegroundColor Yellow
    $senha = Read-Host "Digite sua senha do banco Supabase (ex: 36@Artropodes)" -AsSecureString
    $senha | ConvertFrom-SecureString | Out-File $senhaArquivo
    Write-Host "✅ Senha criptografada salva com segurança em: $senhaArquivo"
} else {
    Write-Host "🔐 Senha segura já existente — carregando..."
    $senha = Get-Content $senhaArquivo | ConvertTo-SecureString
}

# Converte senha criptografada para texto puro em tempo de execução (memória apenas)
$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($senha)
$senhaPura = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
$senhaCodificada = [uri]::EscapeDataString($senhaPura)

# ===================== 🌐 CONFIGURAÇÃO BASE =====================
$DB_URL = "db.kpzzekflqpoeccnqfkng.supabase.co"
$PSQL_PATH = "C:\Program Files\PostgreSQL\17\bin\psql.exe"
$LOG_FILE = "C:\Users\Administrador\pecuariatech\tri360_secure_log.txt"

# ===================== 🧠 1️⃣ VERIFICAÇÃO DE AMBIENTE =====================
Write-Host "🧠 [1/4] Diagnóstico inicial..."
if (-not (Test-Path $PSQL_PATH)) {
    Write-Host "⚠️ Cliente PostgreSQL não encontrado. Instalando..." -ForegroundColor Yellow
    winget install --source winget PostgreSQL.PostgreSQL.17
} else {
    Write-Host "✅ Cliente PostgreSQL detectado."
}
$env:PATH += ";C:\Program Files\PostgreSQL\17\bin"

# ===================== 🌍 2️⃣ TESTE DE CONEXÃO =====================
Write-Host "🌐 [2/4] Testando conexão com Supabase..."
$connectionString = "postgresql://postgres:$senhaCodificada@$DB_URL:5432/postgres"
try {
    $test = & $PSQL_PATH $connectionString -c "SELECT version();" 2>&1
    if ($test -match "PostgreSQL") {
        Write-Host "✅ Conexão estabelecida com Supabase."
    } else {
        throw "Falha ao conectar. Detalhes: $test"
    }
}
catch {
    Write-Host "❌ Erro de conexão com Supabase. Verifique credenciais." -ForegroundColor Red
    Add-Content $LOG_FILE "[$(Get-Date)] Falha de conexão: $_"
    exit
}

# ===================== 🧩 3️⃣ REPARO E CRIAÇÃO DE TABELA =====================
Write-Host "🧩 [3/4] Verificando e criando tabela logs_reparo..."
$sql = @"
create table if not exists public.logs_reparo (
  id bigint generated by default as identity primary key,
  data_execucao timestamptz default now(),
  arquivos_verificados int,
  arquivos_corrigidos int,
  arquivos_padronizados int,
  mensagem text,
  sucesso boolean default true
);
alter table public.logs_reparo enable row level security;
drop policy if exists "Permitir insercoes via API" on public.logs_reparo;
create policy "Permitir insercoes via API"
on public.logs_reparo
for insert
to public
with check (true);
"@
& $PSQL_PATH $connectionString -c $sql
Write-Host "✅ Tabela logs_reparo verificada e funcional." -ForegroundColor Green

# ===================== 🧾 4️⃣ LOGS E VALIDAÇÃO FINAL =====================
$mensagem = "Execução Tri360 Secure completa — conexão e estrutura válidas."
$hash = (Get-FileHash $LOG_FILE -Algorithm SHA256).Hash
Add-Content $LOG_FILE "[$(Get-Date)] $mensagem | Hash: $hash"
Write-Host "📁 Log seguro salvo em: $LOG_FILE" -ForegroundColor Yellow

Write-Host "🔺 Sistema Triangular 360° — Modo Seguro finalizado com sucesso." -ForegroundColor Cyan
