# ============================================================
# Script: instalar-e-reparar-supabase.ps1
# Autor: Richeles + GPT-5
# Descrição: Cria a tabela logs_reparo, aplica RLS, testa API REST e executa o reparo automático
# ============================================================

Write-Host "🚀 Iniciando instalação da tabela logs_reparo e reparo automático..." -ForegroundColor Cyan

# === CONFIGURAÇÕES ===
$pasta = "C:\Users\Administrador\pecuariatech"
$SUPABASE_URL = "https://kpzzekflqpoeccnqfkng.supabase.co"
$SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwenpla2ZscXBvZWNjbnFma25nIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDgwNzE1MiwiZXhwIjoyMDY2MzgzMTUyfQ.8zy_xc93iJVdrIPrdP-iy8XN9GlVWkE0epmrguca3iA"

# === SQL CORRIGIDO (compatível com PostgreSQL 15+) ===
$sql = @"
CREATE TABLE IF NOT EXISTS public.logs_reparo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_execucao TIMESTAMPTZ DEFAULT now(),
  arquivos_verificados INT,
  arquivos_corrigidos INT,
  arquivos_padronizados INT,
  mensagem TEXT,
  sucesso BOOLEAN DEFAULT TRUE
);

ALTER TABLE public.logs_reparo ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir insercoes via API" ON public.logs_reparo;

CREATE POLICY "Permitir insercoes via API"
ON public.logs_reparo
FOR INSERT
TO public
WITH CHECK (true);
"@

# === EXECUTAR SQL VIA API ===
try {
    Invoke-RestMethod `
        -Uri "$SUPABASE_URL/sql/v1" `
        -Method Post `
        -Headers @{
            "apikey" = $SUPABASE_SERVICE_KEY
            "Authorization" = "Bearer $SUPABASE_SERVICE_KEY"
            "Content-Type" = "application/json"
        } `
        -Body (@{ query = $sql } | ConvertTo-Json)

    Write-Host "✅ Tabela logs_reparo criada e política aplicada com sucesso!" -ForegroundColor Green
}
catch {
    Write-Host "❌ Erro ao criar tabela: $($_.Exception.Message)" -ForegroundColor Red
}

# === TESTAR ENDPOINT REST ===
try {
    $testBody = @{
        arquivos_verificados = 5
        arquivos_corrigidos = 1
        arquivos_padronizados = 4
        mensagem = "Teste de integração após instalação"
        sucesso = $true
    } | ConvertTo-Json

    Invoke-RestMethod `
        -Uri "$SUPABASE_URL/rest/v1/logs_reparo" `
        -Method Post `
        -Headers @{
            "apikey" = $SUPABASE_SERVICE_KEY
            "Authorization" = "Bearer $SUPABASE_SERVICE_KEY"
            "Content-Type" = "application/json"
            "Prefer" = "return=minimal"
        } `
        -Body $testBody

    Write-Host "☁️ Endpoint REST ativo e inserção de teste bem-sucedida!" -ForegroundColor Green
}
catch {
    Write-Host "⚠️ Erro ao testar endpoint REST: $($_.Exception.Message)" -ForegroundColor Yellow
}

# === EXECUTAR SCRIPT DE REPARO ===
if (Test-Path "$pasta\reparar-bom-v4.1.ps1") {
    Write-Host "`n🧩 Executando reparo automático (reparar-bom-v4.1.ps1)..." -ForegroundColor Cyan
    & "$pasta\reparar-bom-v4.1.ps1"
} else {
    Write-Host "⚠️ Script reparar-bom-v4.1.ps1 não encontrado." -ForegroundColor Red
}

Write-Host "`n🏁 Instalação e reparo concluídos." -ForegroundColor Cyan
Write-Host "💡 Verifique no Supabase → Table Editor → logs_reparo para confirmar a inserção." -ForegroundColor White
