'use client';
// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/acesso-negado" | "/admin" | "/cloud/status" | "/cloudsync" | "/dashboard" | "/login" | "/mapa" | "/teste" | "/triangulo360" | "/ultra-rastreabilidade" | "/ultrabiologica/status"
type AppRouteHandlerRoutes = "/api/animal/alimentacao" | "/api/animal/cadastro" | "/api/animal/confinamento" | "/api/animal/piquete" | "/api/animal/tratamento" | "/api/ultra/health" | "/api/ultra/ping" | "/api/ultra/stats" | "/api/ultra/status" | "/api/ultrachat" | "/api/ultrachat/A" | "/api/ultrachat/B" | "/api/ultrachat/C" | "/api/ultrachat/D" | "/api/ultrachat/webhook"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/acesso-negado": {}
  "/admin": {}
  "/api/animal/alimentacao": {}
  "/api/animal/cadastro": {}
  "/api/animal/confinamento": {}
  "/api/animal/piquete": {}
  "/api/animal/tratamento": {}
  "/api/ultra/health": {}
  "/api/ultra/ping": {}
  "/api/ultra/stats": {}
  "/api/ultra/status": {}
  "/api/ultrachat": {}
  "/api/ultrachat/A": {}
  "/api/ultrachat/B": {}
  "/api/ultrachat/C": {}
  "/api/ultrachat/D": {}
  "/api/ultrachat/webhook": {}
  "/cloud/status": {}
  "/cloudsync": {}
  "/dashboard": {}
  "/login": {}
  "/mapa": {}
  "/teste": {}
  "/triangulo360": {}
  "/ultra-rastreabilidade": {}
  "/ultrabiologica/status": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}

