'use client';
// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/acesso-negado/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/acesso-negado">> = Specific
  const handler = {} as typeof import("../../app/acesso-negado/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cloud/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cloud/status">> = Specific
  const handler = {} as typeof import("../../app/cloud/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cloudsync/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cloudsync">> = Specific
  const handler = {} as typeof import("../../app/cloudsync/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mapa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mapa">> = Specific
  const handler = {} as typeof import("../../app/mapa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teste/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teste">> = Specific
  const handler = {} as typeof import("../../app/teste/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/triangulo360/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/triangulo360">> = Specific
  const handler = {} as typeof import("../../app/triangulo360/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ultra-rastreabilidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ultra-rastreabilidade">> = Specific
  const handler = {} as typeof import("../../app/ultra-rastreabilidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ultrabiologica/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ultrabiologica/status">> = Specific
  const handler = {} as typeof import("../../app/ultrabiologica/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/animal/alimentacao/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/animal/alimentacao">> = Specific
  const handler = {} as typeof import("../../app/api/animal/alimentacao/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/animal/cadastro/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/animal/cadastro">> = Specific
  const handler = {} as typeof import("../../app/api/animal/cadastro/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/animal/confinamento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/animal/confinamento">> = Specific
  const handler = {} as typeof import("../../app/api/animal/confinamento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/animal/piquete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/animal/piquete">> = Specific
  const handler = {} as typeof import("../../app/api/animal/piquete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/animal/tratamento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/animal/tratamento">> = Specific
  const handler = {} as typeof import("../../app/api/animal/tratamento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ultra/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ultra/health">> = Specific
  const handler = {} as typeof import("../../app/api/ultra/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ultra/ping/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ultra/ping">> = Specific
  const handler = {} as typeof import("../../app/api/ultra/ping/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ultra/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ultra/stats">> = Specific
  const handler = {} as typeof import("../../app/api/ultra/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ultra/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ultra/status">> = Specific
  const handler = {} as typeof import("../../app/api/ultra/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ultrachat/A/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ultrachat/A">> = Specific
  const handler = {} as typeof import("../../app/api/ultrachat/A/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ultrachat/B/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ultrachat/B">> = Specific
  const handler = {} as typeof import("../../app/api/ultrachat/B/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ultrachat/C/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ultrachat/C">> = Specific
  const handler = {} as typeof import("../../app/api/ultrachat/C/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ultrachat/D/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ultrachat/D">> = Specific
  const handler = {} as typeof import("../../app/api/ultrachat/D/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ultrachat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ultrachat">> = Specific
  const handler = {} as typeof import("../../app/api/ultrachat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ultrachat/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ultrachat/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/ultrachat/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

